### ISSUE TITLE
Moving back to live this project to help the migration to Spring Boot & Spring Cloud?

### ISSUE THREAD

**Issue by laugimethods** [spring-attic/spring-migration-analyzer#10]
Hello,

I'm wondering if it would make sense to restart this project to help the migration of legacy Java applications to Spring Boot & Spring Cloud...

Best regards.

**Comment by wilkinsona** [comment]
Sorry, but we don't have any plans to do that. This project is dormant and is unlikely to be updated.

**Comment by laugimethods** [comment]
Thanks @wilkinsona for your quick answer.

Working on the migration of legacy applications to PCF (after attending https://content.pivotal.io/blog/helping-partners-transform-the-pivotal-platform-acceleration-lab ), I _might_ be interested in contributing to the update of this project. Is it something that could be possible?

**Comment by wilkinsona** [comment]
No, sorry. This project has served its purpose. What you're proposing sounds like it would be better as a new, separate project.
